### ISSUE TITLE
Add `Write(rows  []map[string]interface{})` method to Frame interface

### ISSUE THREAD

**Issue by tebeka** [v3io/frames#15]

**Comment by yaronha** [comment]
@tebeka i assume on the Py side we need to have an extra Write() params which is `rows` (dict of dict, e.g. { "key1":{"v1":5,"v2":6},"key2":{"v1":7}}

alternatively we can have a separate WriteRows() command ?

**Comment by tebeka** [comment]
API (in `FrameAppender`) will be 

```go
WriteRow(index map[string]interface{}, row map[string]interface{}) error
```

**Comment by tebeka** [comment]
Talking to @yaronha, we'll add an update flag
