### ISSUE TITLE
Make Frame tsdb usable

### ISSUE THREAD

**Issue by tebeka** [v3io/frames#150]
We'd like `v3io/v3io-tsdb` use `v3io/frames.Frame`, need to check what is missing and how can we make the imports work.

See [RFC](https://docs.google.com/document/d/1tvmXNXUFp8RGUm28-OXxZR8VBCks4TXafyn5hCI4oVw/edit#) as well.

**Comment by talIguaz** [comment]
Current known gaps between `v3io/v3io-tsdb` and `v3io/frames.Frame`:
The following is a list of features supported in tsdb implementation and lacking in frames.
1. Current tsdb frame supports **Hidden** and **Visible** columns. example: if a user wants `avg` aggregates the DF will have 2 hidden columns (sum,count) and one column that would be shown to the user (avg).
2. Current tsdb frame supports 3 types of Columns: dataColumn, ConcreteColumn, VirtualColumn.
In short: `dataColumn` - for raw data, `concreteColumn` - for data aggregated by raw aggregates (max,sum,etc..), `virtualColumn` - for data aggregated by advanced aggregates (avg, stddev,etc..)
There is some logic when creating a frame to understand which types of columns are needed and infer the dependency columns for the virtualColumns.
3. Option to set a value at a specific index in a column
4. Aggregation logic in `Column`: To support aggregation, when creating a new column you need to specify a `setFunction` which will apply every time you set a data to a specific index. (there is a function for every supported aggregation)
5. Interpolation logic - each column saves it's "data" interpolation function instance, used when filling the column with data.
6. Frame supports two ways to get data: 1) as columns, 2) as series (like prometheus and the tsdb cli). For a series api the result will be a series for every combination of index column and another column.
7. Also while iterating over the columns/series of the Frame need to skip the "hidden" columns (see point 1)

**Comment by tebeka** [comment]
@talIguaz Is the code in some branch? I can seem to find it?

**Comment by tebeka** [comment]
Seems like the right approach will be to have `tsdb` extend `frames.Frame` to required features. It can use it for basic operations and even expose `v3io.Frame` interface.
