### ISSUE TITLE
Reset kv timeout after every successful response from v3io

### ISSUE THREAD

**Issue by tebeka** [v3io/frames#16]

**Comment by tebeka** [comment]
@yaronha I'm guessing you mean `respWaitLoop` in `Appender`. We have a global timeout currently, if we'll reset it on every reply this means the actual timeout might be `timeout * numWrites`. Is that what you want?

**Comment by yaronha** [comment]
@tebeka the idea is to restart the timeout everytime we get a response, i.e. timeout from the last resp not 3 * something. right now we set high timeout since we need to account for all the IOs, w this change the timeout only have to cover a roundtrip latency
